
class MemoryScan(object):
    """
    Yield all records from the given "table" in memory.

    This is really just for testing... in the future our scan nodes
    will read from disk.
    """
    def __init__(self, table):
        self.table = table
        self.idx = 0

    def next(self):
        if self.idx >= len(self.table):
            return None

        x = self.table[self.idx]
        self.idx += 1
        return x

class GroupBy(object):
    """
    Group the child records using the given key function, and aggregate
    using the given aggregate function.

    Note that this implementation reads all child records into memory
    before yielding any output.
    """
    def __init__(self, key_func, agg_func):
        self.key_func = key_func
        self.agg_func = agg_func
        self.groups = None
        self.group_keys = None
        self.idx = 0

    def next(self):
        if self.groups is None:
            # read all child records and group them
            self.groups = {}
            while True:
                x = self.child.next()
                if x is None:
                    break
                key = self.key_func(x)
                if key not in self.groups:
                    self.groups[key] = []
                self.groups[key].append(x)
            self.group_keys = list(self.groups.keys())

        if self.idx >= len(self.group_keys):
            return None

        key = self.group_keys[self.idx]
        records = self.groups[key]
        self.idx += 1
        result = self.agg_func(key, records)
        print("GroupBy result:", result)
        return result

class Projection(object):
    """
    Map the child records using the given map function, e.g. to return a subset
    of the fields.
    """
    def __init__(self, proj):
        self.proj = proj

    def next(self):
        x = self.child.next()
        if x is None:
            return None
        return self.proj(x)


class Selection(object):
    """
    Filter the child records using the given predicate function.

    Yes it's confusing to call this "selection" as it's unrelated to SELECT in
    SQL, and is more like the WHERE clause. We keep the naming to be consistent
    with the literature.
    """
    def __init__(self, predicate):
        self.predicate = predicate


    def next(self):
        x = self.child.next()
        if x is None or self.predicate(x):
            return x
        else:
            return self.next()


class Limit(object):
    """
    Return only as many as the limit, then stop
    """
    def __init__(self, limit ,  offset=0):
        self.limit = limit
        self.offset = offset

    def next(self):
        x = self.child.next()
        if x is None or self.limit  <= 0:
            return None
        if self.offset  > 0 :
            self.offset  -= 1
            return self.next()
        self.limit  -= 1
        return x


class Sort(object):
    """
    Sort based on the given key function
    """
    def __init__(self, key, desc=False):
        self.key = key
        self.desc = desc
        self.arr = None
        self.idx = 0
        self.sorted = False
        
    def next(self):
        if not self.sorted:
            while True:
                x = self.child.next()
                if x is None:
                    break
                if self.arr is None:
                    self.arr = []
                self.arr.append(x)
            self.arr = sorted(self.arr, key=self.key, reverse=self.desc)
            self.sorted = True
        if self.arr is None or self.idx >= len(self.arr):
            return None
        x = self.arr[self.idx]
        self.idx += 1
        return x


def Q(*nodes):
    """
    Construct a linked list of executor nodes from the given arguments,
    starting with a root node, and adding references to each child
    """
    ns = iter(nodes)
    parent = root = next(ns)
    for n in ns:
        parent.child = n
        parent = n
    return root


def run(q):
    """
    Run the given query to completion by calling `next` on the (presumed) root
    """
    while True:
        x = q.next()
        if x is None:
            break
        yield x


if __name__ == '__main__':
    # Test data generated by Claude and probably not accurate!
    birds = (
        ('amerob', 'American Robin', 0.077, True),
        ('baleag', 'Bald Eagle', 4.74, True),
        ('eursta', 'European Starling', 0.082, True),
        ('barswa', 'Barn Swallow', 0.019, True),
        ('ostric1', 'Ostrich', 104.0, False),
        ('emppen1', 'Emperor Penguin', 23.0, False),
        ('rufhum', 'Rufous Hummingbird', 0.0034, True),
        ('comrav', 'Common Raven', 1.2, True),
        ('wanalb', 'Wandering Albatross', 8.5, False),
        ('norcar', 'Northern Cardinal', 0.045, True)
    )
    schema = (
        ('id', str),
        ('name', str),
        ('weight', float),
        ('in_us', bool),
    )

    # ids of non US birds
    assert tuple(run(Q(
        Projection(lambda x: (x[0],)),
        Selection(lambda x: not x[3]),
        MemoryScan(birds)
    ))) == (
        ('ostric1',),
        ('emppen1',),
        ('wanalb',),
    )
    
    # id and weight of 3 heaviest birds
    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Limit(3),
        Sort(lambda x: x[2], desc=True),
        MemoryScan(birds),
    ))) == (
        ('ostric1', 104.0),
        ('emppen1', 23.0),
        ('wanalb', 8.5),
    )
    ## id and weight of 3 lightest birds skipping the lightest one
    assert tuple(run(Q(
        Projection(lambda x: (x[0], x[2])),
        Limit(limit = 3, offset=1),
        Sort(lambda x: x[2], desc=False),
        MemoryScan(birds),
    ))) == (
        ('barswa', 0.019),
        ('norcar', 0.045),
        ('amerob', 0.077),
    )
    ## test the group by and aggregation sum of the third field (weight)

    assert tuple(run(Q(
        GroupBy(lambda x: x[3], lambda key, records: (key, sum(r[2] for r in records))),
        Sort(lambda x: x[3]),
        MemoryScan(birds),
    ))) == (
        (False, 135.5),
        (True, 6.1664),
    )   
    print('ok')


